### ISSUE TITLE
safelist Put 函数多协程下，存在tail 指针无法指到最后一个元素，造成元素消失

### ISSUE THREAD

**Issue by fananchong** [giant-tech/go-service#7]

**Comment by fananchong** [comment]
1. A 元素 Put 协程， 51 行被切出
2. B 、 C 元素 Put , sl.tail 指向 C 
3. A 元素 Put 协程被切近， 55 行会成功插入。即 C 的 next 是 A
4. 62 行交换失败，还是指向 C ， 至此 A 插入后消失

**Comment by meowao** [comment]
> 1. A 元素 Put 协程， 51 行被切出
> 2. B 、 C 元素 Put , sl.tail 指向 C
> 3. A 元素 Put 协程被切近， 55 行会成功插入。即 C 的 next 是 A
> 4. 62 行交换失败，还是指向 C ， 至此 A 插入后消失

按这情况a应该并没有消失,a还是在c.next中存着呢

**Comment by fananchong** [comment]
pop 时，纠正了tail 指针，应该无这个问题
